MedicineHelperApp/Controllers/MedicinePrescriptionController.cs
using AutoMapper;
using MedicineHelper.Business.ServicesImplementations;
using MedicineHelper.Core.Abstractions;
using MedicineHelper.Core.DataTransferObjects;
using MedicineHelper.DataBase.Entities;
using MedicineHelperApp.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using ReflectionIT.Mvc.Paging;
using Serilog;

namespace MedicineHelper.Controllers
{
    [Authorize(Roles = "User")]
    public class MedicinePrescriptionController : Controller
    {
        private readonly IMapper _mapper;
        private readonly IMedicinePrescriptionService _medicinePrescriptionService;
        private readonly IUserService _userService;
        private readonly IMedicineService _medicineService;

        public MedicinePrescriptionController(IMapper mapper, IMedicinePrescriptionService medicinePrescriptionService,
            IUserService userService, IMedicineService medicineService)
        {
            _mapper = mapper;
            _medicinePrescriptionService = medicinePrescriptionService;
            _userService = userService;
            _medicineService = medicineService;
        }

        public async Task<IActionResult> Index(DateTime SearchDateStart, DateTime SearchDateEnd, int pageIndex = 1)
        {
            try
            {
                var emailUser = HttpContext.User.Identity?.Name;
                var userDto = _userService.GetUserByEmailAsync(emailUser);

                if (SearchDateStart == DateTime.MinValue && SearchDateEnd == DateTime.MinValue)
                {
                    var listMedicinePrescription = await _medicinePrescriptionService.GetAllMedicinePrescriptionAsync(userDto.Id);

                    var model = PagingList.Create(listMedicinePrescription, 5, pageIndex);
                    return View(model);
                }
                else
                {
                    var listMedicinePrescription = await _medicinePrescriptionService.GetPeriodMedicinePrescriptionAsync(SearchDateStart, SearchDateEnd, userDto.Id);
                    var model = PagingList.Create(listMedicinePrescription, 5, pageIndex);

                    return View(model);
                }
            }
            catch (Exception e)
            {
                Log.Error($"{e.Message}");
                return StatusCode(500);
            }
        }

        [HttpGet]
        public async Task<IActionResult> CreateAsync(Guid id)
        {
            try
            {
                var medicines = await _medicineService.GetAllMedicineAsync();
                var model = new MedicinePrescriptionModel();
                model.AppointmentId = id;
                model.MedicineList = new SelectList(medicines, "Id", "NameOfMedicine");
                model.ReturnUrl = Request.Headers["Referer"].ToString();

                return View(model);
            }
            catch (Exception e)
            {
                Log.Error($"{e.Message}");
                return StatusCode(500);
            }
        }

        [HttpPost]
        public async Task<IActionResult> Create(MedicinePrescriptionModel model)
        {
            try
            {
                var userEmail = HttpContext.User.Identity.Name;
                var userDto = _userService.GetUserByEmailAsync(userEmail);
                var dto = _mapper.Map<MedicinePrescriptionDto>(model);
                dto.UserId = userDto.Id;
                await _medicinePrescriptionService.CreateMedicinePrescriptionAsync(dto);

                return Redirect(model.ReturnUrl);
            }
            catch (Exception e)
            {
                Log.Error($"{e.Message}");
                return StatusCode(500);
            }
        }
        [HttpGet]
        public IActionResult Delete(MedicinePrescriptionModel model)
        {
            try
            {
                
                return View(model);
            }
            catch (Exception e)
            {
                Log.Error($"{e.Message}");
                return StatusCode(500);
            }
        }

        [HttpPost]
        public async Task<IActionResult> Delete(Guid id)
        {
            try
            {
                await _medicinePrescriptionService.DeleteMedicinePrescriptionAsync(id);

                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                Log.Error($"{e.Message}");
                return StatusCode(500);
            }
        }

        [HttpGet]
        public async Task<IActionResult> Details(Guid id)
        {
            try
            {
                var medicine = await _medicineService.GetByIdMedicineAsync(id);
                if (medicine.Instructions != null)
                {
                    return Redirect(medicine.Instructions);
                }
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                Log.Error($"{e.Message}");
                return StatusCode(500);
            }
        }
    }
}

MedicineHelperApp/Views/MedicinePrescription/Create.cshtml
@using MedicineHelperApp.Models;
@model MedicinePrescriptionModel

@{
    ViewData["Title"] = "Add medicine prescription";
    Layout = "_Layout";
}

<div>
    <h2 class="text-center">Add medicine prescription</h2>

    <form asp-controller="MedicinePrescription" asp-action="Create" method="post">
        <div class="mb-3">
            <label for="MedicinesDto.Id" class="form-label">Medicine name:</label>
            <select asp-for="MedicinesDto.Id" asp-items="@Model.MedicineList"></select>
            <a class="btn btn-success" asp-controller="Medicine" asp-action="Create">Add medicine</a>
        </div>
        <div class="mb-3">
            <label for="StartOfAdmission" class="form-label">Start of admission:</label>
            <input asp-for="StartOfAdmission" type="datetime-local" class="form-control" id="StartOfAdmission" value="@DateTime.UtcNow" required />
            <span asp-validation-for="StartOfAdmission" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label for="EndOfAdmission" class="form-label">End of admission:</label>
            <input asp-for="EndOfAdmission" type="datetime-local" class="form-control" id="EndOfAdmission" value="@DateTime.UtcNow" not required />
        </div>
        <div class="mb-3">
            <label for="MedicineDose" class="form-label">Medicine dose:</label>
            <input asp-for="MedicineDose" type="text" id="MedicineDose" />
        </div>
        <div class="mb-3">
            <label for="MedicinePrice" class="form-label">Medicine price $:</label>
            <input asp-for="MedicinePrice" type="number" id="MedicinePrice" />
        </div>
        <div>
            <input asp-for="AppointmentId" type="hidden" />
            <input asp-for="ReturnUrl" type="hidden" />
        </div>
        <input type="submit" class="btn btn-success" value="Add" />
        <a class="btn btn-primary" role="button" asp-controller="MedicinePrescription" asp-action="Index">Back</a>
    </form>
</div>

@section Scripts
    {
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
}

MedicineHelperApp/Views/MedicinePrescription/Delete.cshtml
@model MedicinePrescriptionModel

@{
    ViewData["Title"] = "Delete medicine prescription";
    Layout = "_Layout";
}

<div align="center">
    <h4>Confirm delete</h4>
</div>
<form align="center" asp-controller="MedicinePrescription" asp-action="Delete" method="post" asp-route-id="@Model.Id">
    <div >
        <input type="submit" class="btn btn-danger m-1" value="Delete" />
        <a class="btn btn-primary m-1" role="button" asp-controller="MedicinePrescription" asp-action="Index">Cancel</a>
    </div>
</form>

@section Scripts
    {
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
}

MedicineHelperApp/Views/MedicinePrescription/Index.cshtml
@using ReflectionIT.Mvc.Paging;
@addTagHelper *, ReflectionIT.Mvc.Paging
@model PagingList<MedicineHelper.Core.DataTransferObjects.MedicinePrescriptionDto>

@{
    ViewData["Title"] = "Medicine prescription";
    Layout = "_layout";
}

<div class="text-center">
    <h2 class="text-center">Medicine prescription</h2>
    <form asp-controller="MedicinePrescription" asp-action="Index" method="get">
        <div>
            Start date: <input type="date" name="SearchDateStart" value="@DateTime.UtcNow" />
            End date: <input type="date" name="SearchDateEnd" />
            <input type="submit" value="Search" />
        </div>
    </form>
</div>

<p>
    <a class="btn btn-success" asp-action="Create">Add medicine prescription</a>
</p>

<table class="table">
    <thead>
        <tr>
            <th>
                Name of medicine
            </th>
            <th>
                Start of admission
            </th>
            <th>
                End of admission
            </th>
            <th>
                Medicine dose
            </th>
            <th>
                Medicine price
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.ActionLink(item.MedicinesDto.NameOfMedicine, "Details", "MedicinePrescription", new { id = item.MedicinesDto.Id }, new { @class = "tempClass" })
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.StartOfAdmission)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.EndOfAdmission)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.MedicineDose)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.MedicinePrice)
                </td>
                <td>
                    <a class="btn btn-danger" asp-controller="MedicinePrescription" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

<div aria-label="Medicine prescription">
    <vc:pager paging-list="@Model" />
</div>

@section Scripts
    {
        <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
        <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>

        <script src="~/js/modalWindow.js" asp-append-version="true"></script>
}