MedicineHelperApp/Controllers/ClinicController.cs
using AutoMapper;
using MedicineHelper.Core.Abstractions;
using MedicineHelper.Core.DataTransferObjects;
using MedicineHelperApp.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Serilog;

namespace MedicineHelper.Controllers
{
    [Authorize(Roles = "User")]
    public class ClinicController : Controller
    {
        private readonly IMapper _mapper;
        private readonly IClinicService _clinicService;

        public ClinicController(IMapper mapper, IClinicService clinicService)
        {
            _mapper = mapper;
            _clinicService = clinicService;
        }

        [HttpGet]
        public IActionResult Create()
        {
            try
            {
                var model = new ClinicModel();
                model.ReturnUrl = Request.Headers["Referer"].ToString();

                return View(model);
            }
            catch (Exception e)
            {
                Log.Error($"{e.Message}");
                return StatusCode(500);
            }
        }

        [HttpPost]
        public async Task<IActionResult> Create(ClinicModel model)
        {
            try
            {
                var dto = _mapper.Map<ClinicDto>(model);
                await _clinicService.CreateClinicAsync(dto);

                return Redirect(model.ReturnUrl);
            }
            catch (Exception e)
            {
                Log.Error($"{e.Message}");
                return StatusCode(500);
            }
        }

        [HttpGet]
        public async Task<IActionResult> DetailsClinic(Guid id)
        {
            try
            {
                var dto = await _clinicService.GetByIdClinicAsync(id);

                return View(dto);
            }
            catch (Exception e)
            {
                Log.Error($"{e.Message}");
                return StatusCode(500);
            }
        }
    }
}

MedicineHelperApp/Controllers/MedicineСheckupController.cs
using AutoMapper;
using MedicineHelper.Business.ServicesImplementations;
using MedicineHelper.Core.Abstractions;
using MedicineHelper.Core.DataTransferObjects;
using MedicineHelperApp.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using ReflectionIT.Mvc.Paging;
using Serilog;

namespace MedicineHelper.Controllers
{
    [Authorize(Roles = "User")]
    public class MedicineСheckupController : Controller
    {
        private readonly IMapper _mapper;
        private readonly IMedicineСheckupService _medicineСheckupService;
        private readonly IUserService _userService;
        private readonly IClinicService _clinicService;

        public MedicineСheckupController(IMapper mapper, IMedicineСheckupService medicineCheckupService,
            IUserService userService, IClinicService clinicService)
        {
            _mapper = mapper;
            _medicineСheckupService = medicineCheckupService;
            _userService = userService;
            _clinicService = clinicService;
        }

        [HttpGet]
        public async Task<IActionResult> Index(DateTime SearchDateStart, DateTime SearchDateEnd, int pageIndex = 1)
        {
            try
            {
                var emailUser = HttpContext.User.Identity?.Name;
                var userDto = _userService.GetUserByEmailAsync(emailUser);
                if (SearchDateStart == DateTime.MinValue && SearchDateEnd == DateTime.MinValue)
                {
                    var listMedicineCheckup = await _medicineСheckupService.GetAllMedicineСheckupAsync(userDto.Id);

                    var model = PagingList.Create(listMedicineCheckup, 5, pageIndex);
                    return View(model);
                }
                else
                {
                    var listMedicineCheckup = await _medicineСheckupService.GetPeriodMedicineСheckupAsync(SearchDateStart, SearchDateEnd, userDto.Id);
                    var model = PagingList.Create(listMedicineCheckup, 5, pageIndex);

                    return View(model);
                }
            }
            catch (Exception e)
            {
                Log.Error($"{e.Message}");
                return StatusCode(500);
            }
        }

        [HttpGet]
        public async Task<IActionResult> Create(Guid? id)
        {
            try
            {
                var clinicDto = await _clinicService.GetClinicAsync();
                var model = new MedicineСheckupModel();
                model.AppointmentId = id;
                model.ClinicList = new SelectList(clinicDto, "Id", "Name");
                model.ReturnUrl = Request.Headers["Referer"].ToString();
                if (model.ReturnUrl == "https://localhost:7226/Clinic/Create")
                {
                    model.ReturnUrl = "https://localhost:7226/MedicineCheckup/Index";
                }

                return View(model);
            }
            catch (Exception e)
            {
                Log.Error($"{e.Message}");
                return StatusCode(500);
            }
        }

        [HttpPost]
        public async Task<IActionResult> Create(MedicineСheckupModel model)
        {
            try
            {
                var userEmail = HttpContext.User.Identity.Name;
                var userDto = _userService.GetUserByEmailAsync(userEmail);
                model.UserId = userDto.Id;
                var dto = _mapper.Map<MedicineСheckupDto>(model);
                await _medicineСheckupService.CreateMedicineСheckupAsync(dto);

                return Redirect(model.ReturnUrl);
            }
            catch (Exception e) { Log.Error($"{e.Message}"); return StatusCode(500); }
        }
        [HttpGet]
        public IActionResult Delete(Guid id, string name)
        {
            try
            {
                var model = new MedicineСheckupModel();
                model.NameOfMedicalCheckUp = name;
                model.Id = id;
                return View(model);
            }
            catch (Exception e)
            {
                Log.Error($"{e.Message}");
                return StatusCode(500);
            }
        }

        [HttpPost]
        public async Task<IActionResult> Delete(Guid id)
        {
            try
            {
                await _medicineСheckupService.DeleteMedicineСheckup(id);

                return RedirectToAction("Index", "MedicineСheckup");
            }
            catch (Exception e)
            {
                Log.Error($"{e.Message}");
                return StatusCode(500);
            }
        }
    }
}

MedicineHelperApp/Views/MedicineСheckup/Create.cshtml
@model MedicineСheckupModel

@{
    ViewData["Title"] = "Add medicine checkup";
    Layout = "_Layout";
}

<div>
    <h2 class="text-center">Add medicine checkup</h2>

    <form asp-controller="MedicineСheckup" asp-action="Create" method="post">
        <div class="mb-3">
            <label for="NameOfMedicalCheckUpСheckup" class="form-label">Name medicine checkup:</label>
            <input asp-for="NameOfMedicalCheckUp" type="text" class="form-control" id="NameOfMedicalCheckUp" required />
            <span asp-validation-for="NameOfMedicalCheckUp" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label for="DateOfMedicalCheckUp" class="form-label">Date of medicine checkup:</label>
            <input asp-for="DateOfMedicalCheckUp" type="date" class="form-control" id="DateOfMedicalCheckUp" value="@DateTime.UtcNow" required />
            <span asp-validation-for="DateOfMedicalCheckUp" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label for="Note" class="form-label">Note:</label>
            <textarea asp-for="Note" asp-items="@Model.Note" rows="4" width="100%"></textarea>
        </div>
        <div class="mb-3">
            <label for="PriceOfMedicalCheckUp" class="form-label">Price of medicine checkup $:</label>
            <input asp-for="PriceOfMedicalCheckUp" type="number" class="form-control" id="PriceOfMedicalCheckUp" />
        </div>
        <div class="mb-3">
            <label for="ClinicId" class="form-label">Clinic:</label>
            <select asp-for="ClinicId" asp-items="@Model.ClinicList"></select>
            <a class="btn btn-success" asp-controller="Clinic" asp-action="Create">Add clinic</a>
        </div>
        <div>
            <input asp-for="AppointmentId" type="hidden" />
            <input asp-for="ReturnUrl" type="hidden" />
        </div>
        <input type="submit" class="btn btn-success" value="Add" />
        <a class="btn btn-primary" role="button" asp-controller="MedicineСheckup" asp-action="Index">Back</a>
    </form>
</div>

@section Scripts
    {
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
}

MedicineHelperApp/Views/MedicineСheckup/Delete.cshtml
@using MedicineHelperApp.Models;
@model MedicineСheckupModel

@{
    ViewData["Title"] = "Delete medicine checkup";
    Layout = "_Layout";
}

<div align="center">
    <h4>Confirm delete</h4>
</div>
<form align="center" asp-controller="MedicineСheckup" asp-action="Delete" method="post" asp-route-id="@Model.Id">
    <div >
        <input type="submit" class="btn btn-danger m-1" value="Delete" />
        <a class="btn btn-primary m-1" role="button" asp-controller="MedicineСheckup" asp-action="Index">Cancel</a>
    </div>
</form>

@section Scripts
    {
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
}

MedicineHelperApp/Views/MedicineСheckup/Index.cshtml
@using ReflectionIT.Mvc.Paging;
@addTagHelper *, ReflectionIT.Mvc.Paging
@model PagingList<MedicineHelper.Core.DataTransferObjects.MedicineСheckupDto>

@{
    ViewData["Title"] = "Medicine checkup";
    Layout = "_layout";
}

<div class="text-center">
    <h2 class="text-center">Medicine checkup</h2>
    <form asp-controller="MedicineСheckup" asp-action="Index" method="get">
        <div>
            Start date: <input type="date" name="SearchDateStart" value="@DateTime.UtcNow" />
            End date: <input type="date" name="SearchDateEnd" />
            <input type="submit" value="Search" />
        </div>
    </form>
</div>

<p>
    <a class="btn btn-success" asp-action="Create">Add medicine checkup</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                Name of medicine checkup
            </th>
            <th>
                Clinic
            </th>
            <th>
                Date of medicine checkup
            </th>
            <th>
                Price of medicine checkup
            </th>
            <th>
                Note
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.ActionLink(item.ClinicDto.Name, "DetailsClinic", "Clinic", new { id = item.ClinicDtoId }, new { @class = "tempClass" })
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DateOfMedicineСheckup)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PriceOfMedicineСheckup)
                </td>
                <td>
                    @Html.DisplayFor(modelItem=> item.Note)
                </td>
                <td>
                    <a class="btn btn-danger" asp-controller="MedicineСheckup" asp-action="Delete" asp-route-id="@item.Id" asp-route-name="@item.Name">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

<div aria-label="Medicine checkup">
    <vc:pager paging-list="@Model" />
</div>

@section Scripts
    {
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>

    <script src="~/js/modalWindow.js" asp-append-version="true"></script>
}